name: Build and deploy to riverus-contract-app
# Controls when the workflow will run
on:
pull_request:
branches: [master]
jobs:
build:
#The head_ref or source branch of the pull request in a workflow run.
runs-on: ubuntu-latest
env:
      AWS_ACCESS_KEY_ID: AKIA2BNAHQ7V3ATIWREY
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: us-east-1
steps:
        - uses: actions/checkout@v1

        - name: Install dependencies
          run: yarn

        - name: Build
          run: yarn build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: build
            bucket: nikhil-aws
            dist-id: E3D1D0TY9SPLTF
            invalidation: / *

