# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: AKIATYVWHTRPS7JH2TUM
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: ap-southeast-2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
         node-version: "19"
      # Runs a single command using the runners shell
      - name: setup node
        uses: actions/setup-node@v2    
      - name: deployment
        uses: Burnett01/rsync-deployments@5.2 
        with:
            switches: -avzr --delete
            path: ./build/*
            remote_path: /var/www/html/
            remote_host: ec2-13-55-188-89.ap-southeast-2.compute.amazonaws.com
            remote_user: root
            remote_key: "${{ secrets.CONTRACTS_APP_KEY}}"
            folder: /
            bucket: test-optit
            dist-id: E11MDJNWSNXF4E	
            invalidation: / *
