name: Build and deploy
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 19
      - run: rm -rf node_modules
      - run: npm cache clean --force
      - run: CI='' npm run build:staging
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - uses: actions/checkout@master
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: AKIAQEPBFCHW7E7Y47I6
          AWS_SECRET_ACCESS_KEY: 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
        run: |
          aws s3 cp \
          --recursive \
          --acl public-read \
          --region ap-southeast-2 \
          ./build s3://lokesh-test-bucket
