# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: AKIA2BNAHQ7V3ATIWREY
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: us-east-1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build
        run: yarn build

      # Runs a set of commands using the runners shell
      - name: Deploy
        uses: lbertenasco/s3-deploy@v1 
        with:
            folder: build
            bucket: nikhil-aws
            dist-id: E3D1D0TY9SPLTF
            invalidation: / *
