# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: AKIATYVWHTRPS7JH2TUM
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: ap-southeast-2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
         node-version: "19"
      - name: install depend
        run: npm install
      - name: build
        run: npm run build
      - name: Deploy
        run: aws s3 sync ./* s3://test-optit
