# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
jobs:  
  build:
    runs-on: self-hosted  
    steps:    
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Connect to bastion host
        uses: appleboy/ssh-action@master
        with:
          hostname: 44.200.55.68 
          username: ec2-user
          private-key: ${{ secrets.BASTION_PRIVATE_KEY }}
          script: |
            /home/ec2-user/backend.sh
