name: Deployment

on:
  pull_request:
    branches:
      - master

jobs:
  build:
#The head_ref or source branch of the pull request in a workflow run.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "19"
      - run: mkdir build    
      - name: upload
        uses: actions/upload-artifact@v2.2.0
        with: 
          name: build
          path: build 
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:  
          path: build
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: AKIAQEPBFCHW7E7Y47I6
          AWS_SECRET_ACCESS_KEY: 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
        run: |
          aws s3 cp \
          --recursive \
          --acl public-read \
          --region ap-south-1 \
            build s3://lokesh-test-bucket/lokesh/
