name: Deployment

on:
  pull_request:
    branches:
      - master

jobs:
  build:
#The head_ref or source branch of the pull request in a workflow run.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "19"
      - run: mkdir ./build    
      - name: upload
        uses: actions/upload-artifact@v2.2.0
        with: 
          name: build
          path: build 
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:  
          path: ./build
      - name: Deploy to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: AKIAQEPBFCHW7E7Y47I6
          aws_secret_access_key: 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
          aws-region: ap-south-1   
          aws_bucket: lokesh-test-bucket
          source_dir: ./build
          destination_dir: lokesh
