name: Deploy master
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    #env:
    #  git_hash: ${{ git rev-parse --short "$GITHUB_SHA" }}
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2
