name: Deploy master
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    #env:
    #  git_hash: ${{ git rev-parse --short "$GITHUB_SHA" }}
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Set tag name
      id: tag_name
      run: echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      
    - name: Send email notification for deployment job
      if: success()      
      uses: dawidd6/action-send-mail@v3
      with:
        #server_address: smtp.gmail.com
        #server_port: 587
        #username: ${{ secrets.EMAIL_USERNAME }}
        #password: ${{ secrets.EMAIL_PASSWORD }}
        from: 'kastrokiran123@gmail.com'
        to: 'vnikhil342@gmail.com'
        subject: 'Deployment job completed successfully'
        body: 'The deployment job in your workflow completed successfully.'
      
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        body: This is a new release.
