name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Set tag name
        id: tag_name
        run: echo "::set-output name=tag_name::v$(date +%Y%m%d%H%M%S)"
      
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.tag_name.outputs.tag_name }}
          release_name: Release ${{ steps.tag_name.outputs.tag_name }}
          body: This is a new release.
